const messages={
  "pt-BR":{prototype:"PROTÓTIPO NAVEGÁVEL",client:"Cliente verificada",language:"Idioma",welcome:"Início",discover:"Descobrir",invites:"Convites",journey:"Trajeto",wallet:"Carteira",reviews:"Avaliações"},
  "pt-PT":{prototype:"PROTÓTIPO NAVEGÁVEL",client:"Cliente verificada",language:"Idioma",welcome:"Início",discover:"Descobrir",invites:"Convites",journey:"Percurso",wallet:"Carteira",reviews:"Avaliações"}
};
const nav=[['welcome','✦','welcome'],['discover','⌕','discover'],['invites','◇','invites'],['journey','⌁','journey'],['wallet','◈','wallet'],['reviews','☆','reviews']];
const pages={
welcome:()=>`<section class="page hero"><div><span class="eyebrow">COMPANHIA, CULTURA, CONEXÃO</span><h1>Viva a cidade.<br><span class="gradient-text">Não vá só.</span></h1><p class="lead">Encontre companhia verificada para jantares, concertos e experiências culturais — com clareza e respeito em cada etapa.</p><div class="actions"><a class="btn" href="#discover">Explorar experiências</a><a class="btn secondary" href="#verification">Como funciona</a></div></div><div class="visual-card"><span class="status">✓ Perfil verificado</span><div class="profile-line"><span class="avatar">AS</span><div><strong>Ana Sofia</strong><p>Lisboa · Português, English</p></div></div><div class="tags"><span class="tag">Arte contemporânea</span><span class="tag">Jazz</span><span class="tag">Gastronomia</span></div><p>“Uma boa conversa transforma qualquer noite.”</p></div></section>`,
verification:()=>`<section class="page"><span class="eyebrow">CADASTRO E VERIFICAÇÃO</span><h1 class="page-title">Confiança começa antes do encontro.</h1><p class="lead">Ambos os perfis confirmam idade e identidade. Este protótipo apenas explica o processo; não recolhe documentos nem simula aprovação.</p><div class="grid"><article class="card"><span class="metric">01</span><h2>Crie a conta</h2><p>Escolha o perfil operacional e informe apenas os dados necessários.</p></article><article class="card"><span class="metric">02</span><h2>Confirme identidade</h2><p>O resultado deverá vir de fornecedor ou procedimento autorizado.</p></article><article class="card"><span class="metric">03</span><h2>Complete o perfil</h2><p>Idiomas, interesses, disponibilidade e área tornam o match explicável.</p></article></div><div class="notice">Perfis pendentes não aparecem na descoberta nem podem receber convites.</div><a class="btn" href="#discover">Ver descoberta fictícia</a></section>`,
discover:()=>`<section class="page"><span class="eyebrow">DESCOBERTA</span><h1 class="page-title">Uma noite com a sua cara.</h1><p class="lead">Sugestões fictícias por preferências, disponibilidade e área. Os motivos do match ficam visíveis.</p><div class="grid">${[['Ana Sofia','92%','Jazz e gastronomia','Lisboa'],['Caio Mendes','87%','Cinema e arquitetura','São Paulo'],['Inês Rocha','81%','Museus e vinhos','Porto']].map((p,i)=>`<article class="card feature-card"><div class="profile-line"><span class="avatar">${p[0].split(' ').map(x=>x[0]).join('')}</span><div><h2>${p[0]}</h2><p>${p[3]} · verificado</p></div></div><span class="meta">${p[1]} compatível · ${p[2]}</span><p>Disponível no período escolhido e atende à área aproximada.</p><div class="actions"><a class="btn ${i?'secondary':''}" href="#host">Ver perfil</a></div></article>`).join('')}</div></section>`,
host:()=>`<section class="page"><a class="nav-link" href="#discover">← Voltar à descoberta</a><div class="hero"><div><span class="status">✓ Identidade verificada</span><h1 class="page-title">Ana Sofia</h1><p class="lead">Curadora independente, apaixonada por jazz, arte contemporânea e descobertas gastronómicas.</p><div class="tags"><span class="tag">Português</span><span class="tag">English</span><span class="tag">Lisboa centro</span></div><div class="actions"><a class="btn" href="#invite">Convidar Ana</a></div></div><div class="card"><h2>Por que combina</h2><p>✓ Interesses em comum: jazz e gastronomia</p><p>✓ Disponível sexta, 20:00–23:30</p><p>✓ Área escolhida atendida</p><div class="notice">Endereço e contato privado nunca aparecem no perfil público.</div></div></div></section>`,
invite:()=>`<section class="page"><span class="eyebrow">REVISÃO DO CONVITE</span><h1 class="page-title">Tudo claro antes de enviar.</h1><div class="grid"><article class="card"><span class="meta">EXPERIÊNCIA</span><h2>Jazz & jantar</h2><p>Sexta, 2 out. · 20:00<br>Chiado, área aproximada</p></article><article class="card"><span class="meta">COMPANHIA</span><h2>Ana Sofia</h2><p>3h30 · Português<br>Pagamento do serviço: no local</p></article><article class="card"><span class="meta">CRÉDITOS</span><p class="metric">12</p><p>Seriam reservados agora e consumidos somente após aceite mútuo.</p></article></div><div class="notice">Demonstração: o botão não reserva créditos nem envia um convite real.</div><button class="btn" data-demo="Convite fictício preparado. Nenhuma reserva foi criada.">Rever envio fictício</button></section>`,
invites:()=>`<section class="page"><span class="eyebrow">CONVITES</span><h1 class="page-title">Decisões em duas etapas.</h1><div class="card"><span class="status pending">● Aguarda a sua confirmação</span><div class="profile-line"><span class="avatar">AS</span><div><h2>Ana Sofia aceitou</h2><p>Jazz & jantar · sexta às 20:00</p></div></div><p>Consulte novamente perfil, condições, local e modalidade. Só a sua confirmação consumiria a reserva e criaria o encontro.</p><div class="actions"><a class="btn" href="#confirmation">Rever e confirmar</a><button class="btn secondary" data-demo="No produto, a recusa liberaria integralmente a reserva.">Recusar</button></div></div><h2>Outros convites</h2><div class="empty">Nenhum outro convite. Quando houver novidades, aparecerão aqui com um caminho de ação.</div></section>`,
confirmation:()=>`<section class="page"><span class="eyebrow">CONFIRMAÇÃO</span><h1 class="page-title">Prontos para o encontro.</h1><div class="card"><span class="status">✓ Condições revistas</span><div class="timeline"><div class="step done"><i class="step-dot"></i><div><strong>Convite enviado</strong><p>12 créditos reservados</p></div></div><div class="step done"><i class="step-dot"></i><div><strong>Anfitriã aceitou</strong><p>Perfil e condições disponíveis</p></div></div><div class="step active"><i class="step-dot"></i><div><strong>Confirmação da cliente</strong><p>A operação real seria atômica e idempotente</p></div></div></div><div class="notice">Este protótipo não consome créditos, cria encontros ou processa pagamentos.</div><button class="btn" data-demo="Fluxo demonstrado sem executar operação real.">Confirmar apenas a demonstração</button></div></section>`,
journey:()=>`<section class="page"><span class="eyebrow">TRAJETO COM CONSENTIMENTO</span><h1 class="page-title">A caminho, sem falsa precisão.</h1><div class="grid" style="grid-template-columns:2fr 1fr"><div class="map" role="img" aria-label="Mapa ilustrativo, sem localização real"><i class="map-pin"></i></div><article class="card"><span class="status pending">Atualização antiga</span><h2>Ana está a caminho</h2><p>Última posição fictícia às 19:42, há 18 minutos.</p><p>O compartilhamento só existe durante encontro ativo, após consentimento, e pode ser revogado.</p><button class="btn secondary" data-demo="A posição exibida é apenas ilustrativa.">Atualizar demonstração</button></article></div></section>`,
wallet:()=>`<section class="page"><span class="eyebrow">CARTEIRA</span><h1 class="page-title">Créditos, sem surpresas.</h1><div class="grid"><article class="card"><span class="meta">SALDO CONTABILIZADO</span><p class="metric">40</p></article><article class="card"><span class="meta">RESERVAS ATIVAS</span><p class="metric">12</p></article><article class="card"><span class="meta">DISPONÍVEL</span><p class="metric gradient-text">28</p></article></div><div class="card" style="margin-top:18px"><h2>Histórico ilustrativo</h2><p>+ 40 · Crédito promocional fictício <span class="meta">30 set.</span></p><p>◌ 12 · Reserva ilustrativa: Jazz & jantar <span class="meta">ativa</span></p><div class="notice">Pacotes, preços e validade estão em aberto. Não é possível comprar créditos neste protótipo.</div></div></section>`,
reviews:()=>`<section class="page"><span class="eyebrow">AVALIAÇÕES</span><h1 class="page-title">Feedback privado, na hora certa.</h1><div class="card"><span class="status">✓ Elegível após encerramento</span><h2>Como foi a experiência?</h2><p>No produto, apenas participantes após check-in e encerramento podem avaliar uma vez. A publicação ocorre após ambas as respostas ou o prazo configurado.</p><div class="actions"><button class="btn" data-demo="Avaliação fictícia não foi enviada.">Abrir formulário demonstrativo</button><button class="btn secondary" data-demo="Relatos exigem critérios e revisão; não decidem restituição automaticamente.">Relatar problema</button></div></div><h2>Publicadas</h2><div class="empty">Nenhuma avaliação publicada. Endereços e dados de identidade nunca devem aparecer aqui.</div></section>`
};
let locale=localStorage.getItem('underground-locale')||'pt-BR';
function renderNav(route){document.querySelector('#primary-nav').innerHTML=nav.map(([id,icon,key])=>`<a class="nav-link" href="#${id}" ${route===id?'aria-current="page"':''}><span aria-hidden="true">${icon}</span><span>${messages[locale][key]}</span></a>`).join('')}
function translate(){document.documentElement.lang=locale;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=messages[locale][el.dataset.i18n]);document.querySelector('#locale').value=locale}
function render(){const route=location.hash.slice(1)||'welcome';const valid=pages[route]?route:'welcome';renderNav(valid);document.querySelector('#content').innerHTML=pages[valid]();document.querySelector('#route-context').textContent=messages[locale][nav.find(n=>n[0]===valid)?.[2]]||'Underground';document.querySelector('#announcer').textContent=`Página: ${document.querySelector('#route-context').textContent}`;document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#announcer').textContent=button.dataset.demo;button.textContent=button.dataset.demo}));window.scrollTo(0,0)}
document.querySelector('#locale').addEventListener('change',e=>{locale=e.target.value;localStorage.setItem('underground-locale',locale);translate();render()});window.addEventListener('hashchange',render);translate();render();
